isAuto=false
# players
players.0=human
players.1=human
players.2=random
players.3=human
# first can be 0, 1, 2, 3
plays.0.players.0.initialHearts=3H,7H,11H
plays.0.players.1.initialHearts=6H,10H,12H
plays.0.players.2.initialHearts=2H,4H,9H
plays.0.players.3.initialHearts=5H,8H,13H
plays.0.players.0.initialCards=6C,7C,2D,3D,12D,3S,4S,5S,6S
plays.0.players.1.initialCards=3C,5C,9C,10C,11C,13C,4D,11D,10S
plays.0.players.2.initialCards=2C,4C,12C,8D,13D,2S,9S,11S,13S
plays.0.players.3.initialCards=8C,5D,6D,7D,9D,10D,7S,8S,12S
